### ISSUE TITLE
script tag is NULL with webcomponents v1

### ISSUE THREAD

**Issue by manekinekko** [manekinekko/angular-wc-interop#1]
## steps to reproduce
1. switch to branch [webcomponents-v1-polyfill](https://github.com/manekinekko/angular2-wc-interop/tree/webcomponents-v1-polyfill)
2. `npm i -S https://github.com/webcomponents/webcomponentsjs.git#v1` ([see](https://github.com/manekinekko/angular2-wc-interop/blob/master/package.json#L26))
3. include polyfill: `import 'webcomponents.js/webcomponents-lite.js';` ([see](https://github.com/manekinekko/angular2-wc-interop/blob/master/src/polyfills.ts#L21))
4. implement a wc ([see](https://github.com/manekinekko/angular2-wc-interop/blob/master/src/app/web-components/wc-card/wc-card.ts))

```
const template = require('./wc-card.html');
class WcCard extends HTMLElement {
  constructor() {
    super();
  }
  createdCallback() {
    this.render();
  }
  private render() {
    const template = document.querySelector('#template');
    const shadowRoot = this.createShadowRoot();
    shadowRoot.innerHTML = template.toString();
  }

}
(<any>window).customElements.define('sg-card', WcCard);
```
1. include this wc: `import './app/web-components/wc-card/wc-card.ts';` ([see](https://github.com/manekinekko/angular2-wc-interop/blob/master/src/polyfills.ts#L22))
2. load app

![image](https://cloud.githubusercontent.com/assets/1699357/19436996/98f4aeba-9473-11e6-85ff-1c4e355058ff.png)

cc @robdodson

**Comment by robdodson** [comment]
You're loading the dev version of the polyfill because there isn't a built, release version yet. The dev version of the wc polyfill has to be loaded via a script tag in the head.

If you just need custom elements you could load https://github.com/webcomponents/custom-elements/blob/master/custom-elements.min.js which is a release version.

We intend to make a release build of the v1 web components lite polyfill but just haven't gotten around to it yet

**Comment by manekinekko** [comment]
Alright. I'll test it out this WE and let you know
